version: "3.3"
services:
  api:
    build: .
    ports:
      - "7000:7000"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.4.1"
    ports:
      - "27017:27017"
